name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: ${{ github.ref != 'refs/heads/main' }}
        id: release_draft
        env:
          GITHUB_TOKEN: ${{ github.token }}
